version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directories:
      - "/"
      - "/timber-core"
      - "/timber-maven-plugin"
    schedule:
      interval: "weekly"
